[package]
name = "redeemer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking", "wayland"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
avian2d = "0.3.1"
rand = "0.9.2"
bevy_ecs_tiled = { version = "0.9.0", features = ["avian"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
