[package]
name = "redeemer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
avian3d = "0.3.1"
bevy-tnua = "0.24.0"
bevy-tnua-avian3d = "0.5.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
